### ISSUE TITLE
is not working on the latest update

### ISSUE THREAD

**Issue by bipul-mohanto** [knightcrawler25/Optix-PathTracer#14]
I have tried to build the project with latest optix 7.3 and cuda 11.3 with visual studio 2019. However it did not work. Is there any upgradation plan for this project?

**Comment by knightcrawler25** [comment]
The project works with OptiX 5 and the API has changed since version 7. The code in the repo no longer works with new versions of OptiX. I do have plans to upgrade the project but it would not be anytime soon.

Meanwhile, you might find the following Optix repositories helpful:

https://github.com/shocker-0x15/VLR/tree/OptiX7_RE
https://github.com/NVIDIA/OptiX_Apps
https://github.com/ingowald/optix7course
