### ISSUE TITLE
About scene Dinning-room 

### ISSUE THREAD

**Issue by xin-xinhanggao** [knightcrawler25/Optix-PathTracer#2]
Hi!  
Thanks for your amazing job!
Could you please tell me how you convert the dining-room.blend file to many separate obj files? I use blender to read dining-room.blend and then export to obj, but I could only get one big obj file.
Thanks for your help!

**Comment by knightcrawler25** [comment]
Hi,
You can use the split mesh by material feature in Blender. Select an object -> Edit Mode -> Press P -> By Material. Then select the mesh and export only the selected object as an obj file. It takes a while to do it for big scenes since its a manual process. The dining scene took me about an hour or so to specify all the materials (Since I'm using only the Disney BRDF) and export the meshes.

**Comment by Woking-34** [comment]
Hi! Thanks for sharing your work, really nice!

Unfortunately I"m not professional with Blender, would you be so kind to upload the obj files for the DiningRoom/Bedroom scene?

Thanks for your time.

**Comment by knightcrawler25** [comment]
Sure :) I'll upload the files for both the scenes when I get back from work. The bedroom scene is from https://benedikt-bitterli.me/resources/
You'll find lots of interesting scenes on that site as we

**Comment by knightcrawler25** [comment]
I've added all the .obj files with the latest commit into the src/data/data.rar file. Unzip the file in the same folder and you'll be able to run all the scene files :)

**Comment by qzzone** [comment]
Amazing work!
I have a question about the way to generate scene files.
How did you get scene files as such a format? 
If I want to render other scenes, how can I generate such a x.scene file? Thank you!
